Repository hmcts/bulk-scan-ccd-event-handler-sample-app, pull requests merged in 2020-05, with the labels that each got.

#135 Update dependencies
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: ns:bsp, rel:bulk-scan-sample-app-pr-135

#137 Remove deprecated flag for chart install
  Jenkinsfile_CNP
Labels: ns:bsp, rel:bulk-scan-sample-app-pr-137

#138 copy s2s secret too bulk-scan
  infrastructure/main.tf
Labels: ns:bsp, rel:bulk-scan-sample-app-pr-138

#139 fix the secret name
  infrastructure/main.tf
Labels: ns:bsp, rel:bulk-scan-sample-app-pr-139

#142 upgrade java chart
  charts/bulk-scan-sample-app/Chart.yaml
  charts/bulk-scan-sample-app/requirements.yaml
Labels: ns:bsp, rel:bulk-scan-sample-app-pr-142

#143 Upgrade tomcat embedded jars due to CVE-2020-9484
  build.gradle
Labels: ns:bsp, rel:bulk-scan-sample-app-pr-143
