Repository hmcts/bulk-scan-ccd-event-handler-sample-app, pull requests merged in 2020-04, with the labels that each got.

#132 Update dependencies
  build.gradle
Labels: ns:bsp, rel:bulk-scan-sample-app-pr-132

#133 Clean up validation endpoint
  src/main/java/uk/gov/hmcts/reform/bulkscanccdeventhandler/ocrvalidation/controllers/OcrValidationController.java
  src/test/java/uk/gov/hmcts/reform/bulkscanccdeventhandler/controllers/OcrValidationControllerTest.java
Labels: ns:bsp, rel:bulk-scan-sample-app-pr-133

#134 Remove ASE as it is deployed to AKS
  infrastructure/demo.tfvars
Labels: ns:bsp, rel:bulk-scan-sample-app-pr-134
