Repository hmcts/bulk-scan-ccd-event-handler-sample-app, pull requests merged in 2021-12, with the labels that each got.

#249 DTSBPS-801 fix swagger-ui
  src/integrationTest/resources/application.properties
  src/main/java/uk/gov/hmcts/reform/bulkscanccdeventhandler/config/SwaggerConfiguration.java
  src/main/resources/application.yaml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-sample-app-pr-249

#251 remove org.apache.tomcat.embed from dependencymanagement
  build.gradle
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-sample-app-pr-251

#252 Bump log4j version
  build.gradle
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-sample-app-pr-252
