Repository hmcts/bulk-scan-ccd-event-handler-sample-app, pull requests merged in 2022-11, with the labels that each got.

#404 Suppress Spring-security and tomcat-embed vulnerabilities (DTSBPS-1143)
  config/owasp/suppressions.xml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-sample-app-pr-404

#416 DTSBPS-1163: Suppress CVE-2016-1000027
  config/owasp/suppressions.xml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-sample-app-pr-416

#419 DTSBPS-1167: Suppress CVE-2022-29885
  config/owasp/suppressions.xml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-sample-app-pr-419
