Repository hmcts/bulk-scan-ccd-event-handler-sample-app, pull requests merged in 2022-06, with the labels that each got.

#329 Suppress CVE-2022-22976
  config/owasp/suppressions.xml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-sample-app-pr-329

#334 DTSBPS-978: Suppressed CVE-2022-22978
  config/owasp/suppressions.xml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-sample-app-pr-334

#335 DTSBPS-978: Fix CVE 2022 22978
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-sample-app-pr-335

#336 Removed suppressions
  config/owasp/suppressions.xml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-sample-app-pr-336

#338 Suppress CVE-2022-34305
  charts/bulk-scan-sample-app/Chart.yaml
  config/owasp/suppressions.xml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-sample-app-pr-338
