Repository hmcts/bulk-scan-ccd-event-handler-sample-app, pull requests merged in 2022-08, with the labels that each got.

#357 Suppress CVE-2016-1000027
  config/owasp/suppressions.xml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-sample-app-pr-357

#361 Suppress CVE-2022-29885
  config/owasp/suppressions.xml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-sample-app-pr-361

#362 Update transformation request validation (DTSBPS-144)
  src/main/java/uk/gov/hmcts/reform/bulkscanccdeventhandler/transformation/services/TransformationInputToCaseTransformer.java
  src/main/java/uk/gov/hmcts/reform/bulkscanccdeventhandler/transformation/services/TransformationInputValidator.java
  src/test/java/uk/gov/hmcts/reform/bulkscanccdeventhandler/transformation/services/TransformationInputToCaseTransformerTest.java
  src/test/java/uk/gov/hmcts/reform/bulkscanccdeventhandler/transformation/services/TransformationInputValidatorTest.java
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-sample-app-pr-362

#363 cleanup: Remove unused CaseValidator (DTSBPS-144)
  src/main/java/uk/gov/hmcts/reform/bulkscanccdeventhandler/transformation/services/CaseValidator.java
  src/main/java/uk/gov/hmcts/reform/bulkscanccdeventhandler/transformation/services/TransformationInputToCaseTransformer.java
  src/test/java/uk/gov/hmcts/reform/bulkscanccdeventhandler/transformation/services/CaseValidatorTest.java
  src/test/java/uk/gov/hmcts/reform/bulkscanccdeventhandler/transformation/services/TransformationInputToCaseTransformerTest.java
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-sample-app-pr-363

#364 Add backstage configuration file
  catalog-info.yaml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-sample-app-pr-364
