Repository hmcts/bulk-scan-ccd-event-handler-sample-app, pull requests merged in 2023-01, with the labels that each got.

#463 DTSBPS-1235: Suppressed CVE-2021-4277
  config/owasp/suppressions.xml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-sample-app-pr-463

#466 DTSBPS-1236: Suppressed dependencies
  config/owasp/suppressions.xml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-sample-app-pr-466

#492 DTSBPS-1276: cleanup suppressions
  config/owasp/suppressions.xml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-sample-app-pr-492

#491 DTSBPS-1258: Upgraded AppInsights
  Dockerfile
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-sample-app-pr-491
