Repository hmcts/bulk-scan-ccd-event-handler-sample-app, pull requests merged in 2023-02, with the labels that each got.

#497 DTSBPS-1257: Upgrade to Java 17 and checkstyle version
  Dockerfile
  build.gradle
  charts/bulk-scan-sample-app/values.yaml
  config/checkstyle/checkstyle.xml
  lib/AI-Agent.xml
  lib/applicationinsights.json
  src/main/java/uk/gov/hmcts/reform/bulkscanccdeventhandler/ocrvalidation/controllers/OcrValidationController.java
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-sample-app-pr-497

#499 DTSBPS-1293: Suppress CVE-2022-31690, CVE-2022-31692
  config/owasp/suppressions.xml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-sample-app-pr-499

#519 DTSBPS-1318: Suppress CVE-2022-45688
  config/owasp/suppressions.xml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-sample-app-pr-519
